const PDFDocument = require('pdfkit');

/**
 * Generate an invoice PDF and return it as a buffer
 */
const generateInvoicePDF = (invoice, user) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // Header
      doc.fontSize(28).font('Helvetica-Bold').fillColor('#1a1a2e')
        .text('INVOICE', 50, 50);

      doc.fontSize(10).font('Helvetica').fillColor('#666')
        .text(`Invoice #: ${invoice.invoiceNumber}`, 400, 50, { align: 'right' })
        .text(`Date: ${new Date(invoice.issueDate).toLocaleDateString('en-IN')}`, 400, 65, { align: 'right' })
        .text(`Due: ${new Date(invoice.dueDate).toLocaleDateString('en-IN')}`, 400, 80, { align: 'right' });

      // Status badge
      const statusColors = {
        draft: '#95a5a6',
        sent: '#3498db',
        paid: '#27ae60',
        overdue: '#e74c3c',
        cancelled: '#7f8c8d'
      };
      doc.fontSize(10).fillColor(statusColors[invoice.status] || '#666')
        .text(invoice.status.toUpperCase(), 400, 95, { align: 'right' });

      // Divider
      doc.moveTo(50, 120).lineTo(545, 120).strokeColor('#e0e0e0').stroke();

      // From section
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#333')
        .text('FROM:', 50, 140);
      doc.fontSize(10).font('Helvetica').fillColor('#555')
        .text(user.businessName || user.name, 50, 155)
        .text(user.email, 50, 170);

      // To section
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#333')
        .text('TO:', 300, 140);
      doc.fontSize(10).font('Helvetica').fillColor('#555')
        .text(invoice.clientName, 300, 155)
        .text(invoice.clientEmail || '', 300, 170)
        .text(invoice.clientAddress || '', 300, 185);

      // Table header
      const tableTop = 230;
      doc.rect(50, tableTop, 495, 25).fill('#1a1a2e');

      doc.fontSize(9).font('Helvetica-Bold').fillColor('#fff')
        .text('DESCRIPTION', 60, tableTop + 8)
        .text('QTY', 320, tableTop + 8, { width: 50, align: 'center' })
        .text('RATE (₹)', 380, tableTop + 8, { width: 70, align: 'right' })
        .text('AMOUNT (₹)', 460, tableTop + 8, { width: 80, align: 'right' });

      // Table rows
      let yPos = tableTop + 30;
      invoice.items.forEach((item, index) => {
        const bgColor = index % 2 === 0 ? '#f8f9fa' : '#ffffff';
        doc.rect(50, yPos - 5, 495, 25).fill(bgColor);

        doc.fontSize(9).font('Helvetica').fillColor('#333')
          .text(item.description, 60, yPos)
          .text(item.quantity.toString(), 320, yPos, { width: 50, align: 'center' })
          .text(item.rate.toLocaleString('en-IN'), 380, yPos, { width: 70, align: 'right' })
          .text(item.amount.toLocaleString('en-IN'), 460, yPos, { width: 80, align: 'right' });

        yPos += 25;
      });

      // Totals
      yPos += 15;
      doc.moveTo(350, yPos).lineTo(545, yPos).strokeColor('#e0e0e0').stroke();
      yPos += 10;

      doc.fontSize(10).font('Helvetica').fillColor('#555')
        .text('Subtotal:', 370, yPos)
        .text(`₹${invoice.subtotal.toLocaleString('en-IN')}`, 460, yPos, { width: 80, align: 'right' });

      yPos += 20;
      doc.text(`Tax (${invoice.taxRate}%):`, 370, yPos)
        .text(`₹${invoice.taxAmount.toLocaleString('en-IN')}`, 460, yPos, { width: 80, align: 'right' });

      yPos += 25;
      doc.rect(350, yPos - 5, 195, 25).fill('#1a1a2e');
      doc.fontSize(11).font('Helvetica-Bold').fillColor('#fff')
        .text('TOTAL:', 370, yPos)
        .text(`₹${invoice.total.toLocaleString('en-IN')}`, 460, yPos, { width: 80, align: 'right' });

      // Notes
      if (invoice.notes) {
        yPos += 50;
        doc.fontSize(10).font('Helvetica-Bold').fillColor('#333')
          .text('Notes:', 50, yPos);
        doc.fontSize(9).font('Helvetica').fillColor('#666')
          .text(invoice.notes, 50, yPos + 15, { width: 400 });
      }

      // Footer
      doc.fontSize(8).font('Helvetica').fillColor('#999')
        .text('Generated by FinAI — AI-Powered Financial Assistant', 50, 750, { align: 'center', width: 495 });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateInvoicePDF };
